chatroom/chat/urls.py
from django.conf.urls import url

from chat.views import index, room

app_name = 'chat'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^(?P<room_name>[^/]+)/$', room, name='room'),
]

chatroom/config/urls.py
from django.conf.urls import include, url

from django.contrib import admin

urlpatterns = [
    url(r'^chat/', include('chat.urls', namespace='chat')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^admin/', admin.site.urls),
]

chatroom/member/urls.py
from django.conf.urls import url

from member.views import signup, log_out, log_in

app_name = 'member'

urlpatterns = [
    url(r'^$', signup, name='signup'),
    url(r'^logout/$', log_out, name='log_out'),
    url(r'^login/$', log_in, name='log_in'),
]

chatroom/chat/models.py
from django.db import models

from django.utils import timezone


class ChatRoom(models.Model):
    name = models.CharField(
        max_length=20,
        unique=True
    )

    def __str__(self):
        return self.name


class Message(models.Model):
    chatroom = models.ForeignKey(
        'ChatRoom',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        'member.User',
        on_delete=models.CASCADE,
    )
    comment = models.TextField(
        blank=True
    )
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.pk} - {self.comment}'

chatroom/member/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    nickname = models.CharField(
        max_length=10,
    )

    def __str__(self):
        return self.username

chatroom/member/forms.py
import django
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class UserSignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        class_update_fields = ('password1', 'password2')
        for field in class_update_fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
            })

    class Meta:
        model = User
        fields = (
            'username',
            'nickname',
            'password1',
            'password2',
        )
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
        }


class LoginForm(forms.Form):
    """
    is_valid()에서 주어진 username/password를 사용한 authenticate실행
    성공시 login(request)메서드를 사용할 수 있음
    """
    username = forms.CharField(
        widget=forms.TextInput
    )
    password = forms.CharField(
        widget=forms.PasswordInput
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = None

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        self.user = authenticate(username=username, password=password)
        if not self.user:
            raise forms.ValidationError('Invalid login credentials')
        else:
            setattr(self, 'login', self._login)

    def _login(self, request):
        """
        django.contrib.auth.login(request)를 실행

        :param request: django.contrib.auth.login()에 주어질 HttpRequest객체
        :return: None
        """
        return django.contrib.auth.login(request, self.user)

chatroom/chat/views.py
import json

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from django.utils.safestring import mark_safe

from chat.models import ChatRoom, Message


@login_required
def index(request):
    if request.method == 'GET':
        return render(request, 'chat/index.html')
    elif request.method == 'POST':
        form = request.POST.dict()
        roomname = form.get('roomname').lower().replace(
            ' ', '-'
        )
        chatroom, created = ChatRoom.objects.get_or_create(
            name=roomname,
        )
        doc = {
            'roomname': chatroom.name,
        }
        return JsonResponse(doc)


@login_required
def room(request, room_name):
    chatroom = ChatRoom.objects.get(
        name=room_name
    )
    messages = Message.objects.filter(
        author=request.user,
        chatroom=chatroom,
    ).order_by('timestamp')[:30]
    context = {
        'messages': messages,
        'user_pk': request.user.pk,
        'room_name_json': mark_safe(json.dumps(room_name))
    }
    return render(request, 'chat/room.html', context)

chatroom/member/views.py
from django.contrib.auth import login as django_login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect

from member.forms import UserSignUpForm, LoginForm


def signup(request):
    if request.method == 'POST':
        user_form = UserSignUpForm(request.POST, request.FILES)
        if user_form.is_valid():
            user = user_form.save()
            django_login(request, user)
            return redirect('chat:index')
    else:
        user_form = UserSignUpForm()
    context = {
        'user_form': user_form
    }
    return render(request, 'member/signup.html', context)


def log_in(request):
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            login_form.login(request)
            return redirect('chat:index')
        else:
            return HttpResponse('Login credential invalid')
    else:
        login_form = LoginForm()
    context = {
        'login_form': login_form,
    }
    return render(request, 'member/login.html', context)


@login_required
def log_out(request):
    logout(request)
    return redirect('chat:index')

chatroom/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Chat Room</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
</head>
<body>
<div>
    <nav class="navbar navbar-default">
        <div class="col-lg-6 col-lg-offset-3
				col-md-8 col-md-offset-2
				col-sm-10 col-sm-offset-1
				col-xs-12">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-nav">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'chat:index' %}">Chat Room</a>
            </div>
            <div class="collapse navbar-collapse" id="top-nav">
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'member:log_out' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'member:log_in' %}">Login</a></li>
                        <li><a href="{% url 'member:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="col-lg-6 col-lg-offset-3
				col-md-8 col-md-offset-2
				col-sm-10 col-sm-offset-1
				col-xs-12">
        {% block content %}
        {% endblock %}
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src={% static 'bootstrap/js/bootstrap.min.js' %}></script>
<script>
    // csrf
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?

                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                // Only send the token to relative URLs i.e. locally.
                xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
            }
        }
    });
</script>
{% block inline_script %}
{% endblock %}
</body>
</html>

chatroom/templates/chat/index.html
{% extends 'base.html' %}

<body>
{% block content %}
    What chat room would you like to enter?<br/>
    <input id="room-name-input" type="text" size="100"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>
{% endblock %}

{% block inline_script %}
<script>
    document.querySelector('#room-name-input').focus();
    document.querySelector('#room-name-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#room-name-submit').click();
        }
    };

    $('#room-name-submit').on('click', function() {
        var roomName = $('#room-name-input').val();
        $.ajax({
            url: '/chat/',
            type: 'POST',
            dataType: 'json',
            data: {
                'roomname': roomName
            },
            success: function(res) {
                window.location.pathname = '/chat/' + res['roomname'] + '/';
            }
        })
    });
</script>
{% endblock %}

chatroom/templates/chat/room.html
{% extends 'base.html' %}
{% block content %}
    <textarea id="chat-log" cols="100" rows="20">
        {% for message in messages %}
            {{ message.comment }}
        {% endfor %}
    </textarea><br/>
    <input id="chat-message-input" type="text" size="100"/><br/>
    <input id="chat-message-submit" type="button" value="Send"/>
{% endblock %}
{% block inline_script %}
    <script>
        var roomName = {{ room_name_json }};
        var user_pk = {{ user_pk }};
        var chatSocket = new WebSocket(
            'ws://' + window.location.host +
            '/ws/chat/' + roomName + '/');

        chatSocket.onmessage = function (e) {
            var data = JSON.parse(e.data);
            var message = data['message'];
            document.querySelector('#chat-log').value += (message + '\n');
        };

        chatSocket.onclose = function (e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function (e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function (e) {
            var messageInputDom = document.querySelector('#chat-message-input');
            var message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'user_pk': user_pk,
                'roomname': roomName,
                'message': message
            }));

            messageInputDom.value = '';
        };
    </script>
{% endblock %}

chatroom/templates/member/login.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {% for field in login_form %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
		<label
			for="{{ field.auto_id }}">
			{{ field.label }}
		</label>
		<div>
			{{ field }}
			{% if field.errors %}
				{% for error in field.errors %}
				<span class="help-block">{{ error }}</span>
				{% endfor %}
			{% endif %}
		</div>
	</div>
    {% endfor %}
    {% if login_form.non_field_errors %}
		{% for error in login_form.non_field_errors %}
		<p class="text-danger">{{ error }}</p>
		{% endfor %}
	{% endif %}
    <button class="btn btn-primary btn-block">로그인</button>
</form>
{% endblock %}

chatroom/templates/member/signup.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {% for field in user_form %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
		<label
			for="{{ field.auto_id }}">
			{{ field.label }}
		</label>
		<div>
			{{ field }}
			{% if field.errors %}
				{% for error in field.errors %}
				<span class="help-block">{{ error }}</span>
				{% endfor %}
			{% endif %}
		</div>
	</div>
    {% endfor %}
    {% if user_form.non_field_errors %}
		{% for error in user_form.non_field_errors %}
		<p class="text-danger">{{ error }}</p>
		{% endfor %}
	{% endif %}
    <button class="btn btn-primary btn-block">로그인</button>
</form>
{% endblock %}